name: Auto approve and merge Dependabot
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      uses: bdougie/automerge-action@de631dd9e7650aebeeb115e3fdd7377526bc40d3
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
