name: Auto approve and merge Dependabot
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      uses: bdougie/automerge-action@bot
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
